name: Node Docker CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Node Kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Paketleri yükle
        run: npm install

      - name: Test çalıştır
        run: npm test

      - name: Docker Build
        run: docker build -t my-node-app .

      - name: AWS Deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker rmi my-node-app || true
            docker run -d -p 3000:3000 my-node-app